{% set name = "aiida-siesta" %}
{% set version = "2.0.0" %}
{% set build = 0 %}
{% set name_code = name + ".code" %}

package:
  name: {{ name|lower }}.meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-siesta-{{ version }}.tar.gz
  sha256: 32c29ec0dcc1b9c685452470a5edfb2ca07b23390b47067f6429c154fbdef83f

build:
  number: {{ build }}
  noarch: python

requirements:
  run:
    - {{ pin_subpackage(name, exact=True) }}
    - {{ pin_subpackage(name_code, exact=True) }}

outputs:

  - name: {{ name }}
    build:
      noarch: python
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - aiida-core >=1.3.0,<2
        - aiida-pseudo >=0.6.2
        - ase >=3.18,<4.0.0
        - python >=3.6
        - seekpath >=1.9.3,<2
        - sisl
      run_constrained:
        - {{ name_code }} =={{ version }}
    test:
      imports:
        - aiida_siesta
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name_code }}
    build:
      noarch: python
    requirements:
      run:
        - siesta =4
    test:
      commands:
        - which siesta

about:
  home: https://github.com/siesta-project/aiida_siesta_plugin
  summary: A plugin for Siesta's basic functionality within the AiiDA framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
